#!/usr/bin/env python3
"""
Combined Visualization Script for LOESS Examples.

This script generates plots for all the CSV data generated by `cargo run --example visual`.
It includes:
1. Degree Comparison
2. Fraction Comparison
3. Intervals Comparison
4. Robustness Comparison
5. LOESS Concept
6. Multivariate LOESS

Usage:
    python3 plot.py [target]

    If no target is specified, 'all' plots are generated.
"""

import sys
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import os

INPUT_DIR = 'output/visual'
OUTPUT_DIR = 'output/fig'

# Optimized SVG settings
plt.rcParams['svg.fonttype'] = 'none'


def check_file(filename):
    filepath = os.path.join(INPUT_DIR, filename)
    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found. Run 'cargo run --bin visual' first.")
        return False
    return True

def get_input_path(filename):
    return os.path.join(INPUT_DIR, filename)

def get_output_path(filename):
    return os.path.join(OUTPUT_DIR, filename)

def plot_degree_comparison():
    if not check_file('degree_comparison.csv'): return
    print("Plotting Degree Comparison...")
    
    df = pd.read_csv(get_input_path('degree_comparison.csv'))
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    # Left: Full comparison
    ax1 = axes[0]
    ax1.plot(df['x'], df['y_noisy'], 'o', markersize=3, alpha=0.4, color='gray', markeredgewidth=0, label='Noisy data', rasterized=True)
    ax1.plot(df['x'], df['y_true'], 'k-', lw=1.5, label='True signal', alpha=0.7)
    ax1.plot(df['x'], df['y_lowess'], 'b-', lw=2, label='LOWESS (Linear)')
    ax1.plot(df['x'], df['y_loess'], 'r-', lw=2, label='LOESS (Quadratic)')
    ax1.set_xlabel('x', fontsize=12)
    ax1.set_ylabel('y', fontsize=12)
    ax1.set_title('LOWESS vs LOESS: Full View', fontsize=14)
    ax1.legend(loc='upper right')
    ax1.grid(True, alpha=0.3)

    # Right: Zoomed on peak
    ax2 = axes[1]
    mask = (df['x'] > -0.6) & (df['x'] < 0.6)
    ax2.plot(df.loc[mask, 'x'], df.loc[mask, 'y_noisy'], 'o', markersize=4, alpha=0.5, color='gray', markeredgewidth=0, label='Noisy data', rasterized=True)
    ax2.plot(df.loc[mask, 'x'], df.loc[mask, 'y_true'], 'k-', lw=2, label='True signal')
    ax2.plot(df.loc[mask, 'x'], df.loc[mask, 'y_lowess'], 'b-', lw=2.5, label='LOWESS (Linear)')
    ax2.plot(df.loc[mask, 'x'], df.loc[mask, 'y_loess'], 'r-', lw=2.5, label='LOESS (Quadratic)')
    ax2.set_xlabel('x', fontsize=12)
    ax2.set_ylabel('y', fontsize=12)
    ax2.set_title('Peak Region: Linear Flattens, Quadratic Captures', fontsize=14)
    ax2.legend(loc='lower center')
    ax2.grid(True, alpha=0.3)

    peak_x = df.loc[df['y_true'].idxmax(), 'x']
    peak_true = df['y_true'].max()
    peak_lowess = df.loc[df['y_true'].idxmax(), 'y_lowess']
    
    ax2.annotate(f'Gap = {peak_true - peak_lowess:.3f}', 
                 xy=(peak_x, (peak_lowess + peak_true)/2), 
                 xytext=(0.3, 0.85), fontsize=10, color='blue',
                 arrowprops=dict(arrowstyle='->', color='blue', lw=1.5))

    plt.tight_layout()
    output_file = get_output_path('degree_comparison.svg')
    plt.savefig(output_file, format='svg', dpi=72)
    print(f'Saved to {output_file}')
    plt.close()

def plot_fraction_comparison():
    if not check_file('fraction_comparison.csv'): return
    print("Plotting Fraction Comparison...")
    
    df = pd.read_csv(get_input_path('fraction_comparison.csv'))
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))

    fractions = [0.2, 0.5, 0.9]
    colors = ['#e74c3c', '#3498db', '#2ecc71']
    titles = [
        'Small Fraction (0.2)\nCaptures Details, May Overfit',
        'Medium Fraction (0.5)\nBalanced Smoothing',
        'Large Fraction (0.9)\nVery Smooth, May Underfit'
    ]

    for i, (ax, frac, color, title) in enumerate(zip(axes, fractions, colors, titles)):
        ax.plot(df['x'], df['y_noisy'], 'o', markersize=3.5, alpha=0.3, color='gray', markeredgewidth=0, label='Noisy data', zorder=1, rasterized=True)
        ax.plot(df['x'], df['y_true'], 'k--', lw=1.5, label='True signal', alpha=0.6, zorder=2)
        ax.plot(df['x'], df[f'y_frac_{frac}'], color=color, lw=2.5, 
                label=f'LOESS (fraction={frac})', zorder=3)
        
        ax.set_xlabel('x', fontsize=12)
        ax.set_ylabel('y', fontsize=12)
        ax.set_title(title, fontsize=13, fontweight='bold')
        ax.legend(loc='upper left', fontsize=10)
        ax.grid(True, alpha=0.3)
        
        rmse = ((df[f'y_frac_{frac}'] - df['y_true'])**2).mean()**0.5
        ax.text(0.98, 0.02, f'RMSE: {rmse:.3f}', 
                transform=ax.transAxes, fontsize=11,
                ha='right', va='bottom',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    fig.suptitle('Effect of Fraction Parameter on LOESS Smoothing', 
                 fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    output_file = get_output_path('fraction_comparison.svg')
    plt.savefig(output_file, format='svg', bbox_inches='tight', dpi=72)
    print(f'Saved to {output_file}')
    plt.close()

def plot_intervals_comparison():
    if not check_file('intervals_comparison.csv'): return
    print("Plotting Intervals Comparison...")
    
    df = pd.read_csv(get_input_path('intervals_comparison.csv'))
    fig, ax = plt.subplots(figsize=(10, 8))

    ax.plot(df['x'], df['y_noisy'], 'o', markersize=4.5, alpha=0.6, color='gray', markeredgewidth=0, label='Noisy Data', zorder=1)
    ax.plot(df['x'], df['y_true'], 'k--', lw=1.5, label='True Signal', alpha=0.7, zorder=2)
    ax.plot(df['x'], df['y_smooth'], 'k-', lw=2.5, label='LOESS Fit', zorder=5)

    # Prediction Intervals
    ax.fill_between(df['x'], df['pred_lower'], df['pred_upper'], 
                    alpha=0.2, color='#3b82f6', label='95% Prediction Interval', zorder=3)
    ax.plot(df['x'], df['pred_lower'], linestyle='--', color='#1d4ed8', lw=1.5, alpha=0.6)
    ax.plot(df['x'], df['pred_upper'], linestyle='--', color='#1d4ed8', lw=1.5, alpha=0.6)

    # Confidence Intervals
    ax.fill_between(df['x'], df['conf_lower'], df['conf_upper'], 
                    alpha=0.4, color='#22c55e', label='95% Confidence Interval', zorder=4)
    ax.plot(df['x'], df['conf_lower'], linestyle='--', color='#15803d', lw=1.5, alpha=0.8)
    ax.plot(df['x'], df['conf_upper'], linestyle='--', color='#15803d', lw=1.5, alpha=0.8)

    ax.set_xlabel('x', fontsize=12)
    ax.set_ylabel('y', fontsize=12)
    ax.set_title('Uncertainty Decomposition: Confidence vs Prediction Intervals', fontsize=14, fontweight='bold')
    ax.legend(loc='upper left', fontsize=10, framealpha=0.9)
    ax.grid(True, alpha=0.3)

    avg_pred_width = (df['pred_upper'] - df['pred_lower']).mean()
    avg_conf_width = (df['conf_upper'] - df['conf_lower']).mean()
    
    footnote_text = (
        f"Avg Width Ratio (Pred/Conf): {avg_pred_width/avg_conf_width:.2f}x\n"
        "Confidence Interval: Uncertainty in mean curve (Green)\n"
        "Prediction Interval: Uncertainty for new observations (Blue)"
    )
    plt.subplots_adjust(bottom=0.15)
    fig.text(0.05, 0.02, footnote_text, fontsize=11, family='monospace', va='bottom', ha='left')
    
    output_file = get_output_path('intervals_comparison.svg')
    plt.savefig(output_file, format='svg', bbox_inches='tight', dpi=72)
    print(f'Saved to {output_file}')
    plt.close()

def plot_robustness_comparison():
    if not check_file('robustness_comparison.csv'): return
    print("Plotting Robustness Comparison...")
    
    df = pd.read_csv(get_input_path('robustness_comparison.csv'))
    fig, ax = plt.subplots(figsize=(12, 7))

    ax.plot(df['x'], df['y_noisy'], 'o', markersize=5.5, alpha=0.6, color='gray', markeredgewidth=0, label='Noisy Data', zorder=1)
    ax.plot(df['x'], df['y_true'], 'k--', lw=1.5, label='True Signal', alpha=0.6, zorder=2)
    ax.plot(df['x'], df['y_non_robust'], color='#ef4444', lw=2.0, alpha=0.9, label='Non-Robust (0 iter)')
    ax.plot(df['x'], df['y_robust'], color='#10b981', lw=3.0, alpha=0.95, label='Robust (6 iter)')

    outlier_mask = np.abs(df['y_noisy'] - df['y_true']) > 2.0
    ax.scatter(df.loc[outlier_mask, 'x'], df.loc[outlier_mask, 'y_noisy'], 
               s=80, facecolors='none', edgecolors='#ef4444', lw=1.5, label='Outliers', zorder=5)

    ax.set_xlabel('x', fontsize=12)
    ax.set_ylabel('y', fontsize=12)
    ax.set_ylim(-10, 25)
    ax.set_title('Impact of Robustness Iterations', fontsize=14, fontweight='bold')
    ax.legend(loc='lower left', fontsize=10)
    ax.grid(True, alpha=0.3)
    
    output_file = get_output_path('robustness_comparison.svg')
    plt.savefig(output_file, format='svg', bbox_inches='tight', dpi=72)
    print(f'Saved to {output_file}')
    plt.close()

def plot_loess_concept():
    if not check_file('loess_concept.csv'): return
    print("Plotting LOESS Concept...")
    
    df = pd.read_csv(get_input_path('loess_concept.csv'))
    focus_row = df[df['is_focus'] == 1].iloc[0]
    x0 = focus_row['x']
    y0_fit = focus_row['y_smooth']
    neighborhood = df[df['weight'] > 0]

    fig, ax = plt.subplots(figsize=(12, 7))

    ax.scatter(df['x'], df['y_noisy'], c='lightgray', s=30, alpha=0.5, label='Other Data')
    ax.plot(df['x'], df['y_smooth'], color='black', lw=2, alpha=0.3, label='Global Curve')

    sc = ax.scatter(neighborhood['x'], neighborhood['y_noisy'], 
                    c=neighborhood['weight'], cmap='Blues', s=60, 
                    edgecolor='k', linewidth=0.5, label='Neighborhood')

    ax.plot(neighborhood['x'], neighborhood['y_local_fit_x0'], 
            color='#d97706', lw=3, label='Local Polynomial')

    ax.scatter([x0], [y0_fit], s=150, facecolor='#d97706', edgecolor='white', lw=2, zorder=10, 
               label='Fitted Value')

    ax.set_title(f'How LOESS Works (Focus x={x0:.2f})', fontsize=14, fontweight='bold')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    
    cbar = fig.colorbar(sc, ax=ax)
    cbar.set_label('Weight', fontsize=10)
    
    output_file = get_output_path('loess_concept.svg')
    plt.savefig(output_file, format='svg', bbox_inches='tight', dpi=72)
    print(f'Saved to {output_file}')
    plt.close()

def plot_multivariate_loess():
    if not check_file('multivariate_loess.csv'): return
    print("Plotting Multivariate LOESS...")
    
    df = pd.read_csv(get_input_path('multivariate_loess.csv'))
    n_x = len(df['x'].unique())
    n_y = len(df['y'].unique())
    X = df['x'].values.reshape(n_x, n_y)
    Y = df['y'].values.reshape(n_x, n_y)
    Z_true = df['z_true'].values.reshape(n_x, n_y)
    Z_smooth = df['z_smooth'].values.reshape(n_x, n_y)
    
    fig = plt.figure(figsize=(10, 5))

    # 1. True surface
    ax1 = fig.add_subplot(1, 2, 1, projection='3d')
    surf1 = ax1.plot_surface(X, Y, Z_true, cmap='viridis', alpha=0.9, edgecolor='none', rasterized=True)
    ax1.set_title('True Surface')
    ax1.locator_params(nbins=4)
    cb1 = fig.colorbar(surf1, ax=ax1, shrink=0.5)
    cb1.solids.set_rasterized(True)

    # 2. LOESS smoothed surface
    ax2 = fig.add_subplot(1, 2, 2, projection='3d')
    surf2 = ax2.plot_surface(X, Y, Z_smooth, cmap='magma', alpha=0.9, edgecolor='none', rasterized=True)
    ax2.set_title('LOESS Smoothed')
    ax2.locator_params(nbins=4)
    cb2 = fig.colorbar(surf2, ax=ax2, shrink=0.5)
    cb2.solids.set_rasterized(True)

    plt.tight_layout()
    output_file = get_output_path('multivariate_loess.svg')
    plt.savefig(output_file, format='svg', bbox_inches='tight', dpi=100)
    print(f'Saved to {output_file}')
    plt.close()

if __name__ == "__main__":
    
    # Ensure output directory exists for figures
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    if len(sys.argv) < 2:
        target = 'all'
    else:
        target = sys.argv[1]

    if target == 'all':
        plot_degree_comparison()
        plot_fraction_comparison()
        plot_intervals_comparison()
        plot_robustness_comparison()
        plot_loess_concept()
        plot_multivariate_loess()
    elif target == 'degree':
        plot_degree_comparison()
    elif target == 'fraction':
        plot_fraction_comparison()
    elif target == 'intervals':
        plot_intervals_comparison()
    elif target == 'robustness':
        plot_robustness_comparison()
    elif target == 'concept':
        plot_loess_concept()
    elif target == 'multivariate':
        plot_multivariate_loess()
    else:
        print(f"Unknown target: {target}")
        print("Usage: python3 plot.py [target] (default: all)")
        print("Targets: all, degree, fraction, intervals, robustness, concept, multivariate")
